const {requests,agentRuns,tickets}=require('../dao');
const classifier=require('./classification.service');
const policy=require('./policy.service');
const ticket=require('./ticket.service');
const audit=require('./audit.service');
const {randomUUID}=require('crypto');
const closed=s=>['Resolved','Rejected','Approved'].includes(s);
function decide(req,c){
 const text=req.requestText.toLowerCase(); let decision='HUMAN_REVIEW_REQUIRED',action='ROUTE_TO_IT',route='IT Support',response='',missing=[];
 switch(c.category){
 case 'password':
   if(text.includes('6 times')||text.includes('locked out')){decision='ROUTE_TO_IT';action='ROUTE_TO_IT';response='Your account has exceeded the 5-failed-attempt threshold. IT must manually unlock the account. No approval is required.';} else {decision='RESOLVE';action='RESOLVE';response='You can reset your own password through the self-service portal at any time. No approval is required.';} break;
 case 'vpn':
   if(text.includes('expired')){decision='RESOLVE';action='RESOLVE';response='VPN credentials expire every 90 days and must be renewed by the employee.';} else {decision='HUMAN_REVIEW_REQUIRED';action='REQUEST_INFORMATION';response='VPN access depends on employment type: full-time employees receive access automatically; contractors require manager approval through the access request form.';missing=['employment type'];} break;
 case 'software':
   if(text.includes('not in')||text.includes('non-catalog')||text.includes('browser extension')||text.includes('data-analysis')){decision='ROUTE_TO_SECURITY';action='ROUTE_TO_SECURITY';route='Security';response='This software is outside the approved catalog based on the request. Non-catalog software requires IT Security review, which takes 3–5 business days.';} else {decision='RESOLVE';action='RESOLVE';response='Standard software listed in the approved catalog can be self-installed.';} break;
 case 'printer':
   decision='ROUTE_TO_IT';action='CREATE_TICKET';response='First check the printer queue and restart the print spooler. If the issue persists, an IT ticket should be logged with the printer asset tag.';missing=['printer asset tag'];break;
 case 'email':
   decision='ROUTE_TO_IT';action='RESOLVE';response='The default mailbox quota is 25GB. Archive old mail when nearing quota. Increases beyond 25GB require manager approval and are capped at 50GB.';break;
 case 'guest_wifi': decision='NO_TICKET_REQUIRED';action='NO_TICKET_REQUIRED';response='Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket is required.';break;
 case 'expense_software': decision='ROUTE_TO_IT';action='ROUTE_TO_IT';route='IT Support';response='Finance grants access to the expense management tool. IT can assist with login or technical issues once an account already exists.';break;
 case 'security_incident': decision='ROUTE_TO_SECURITY';action='ROUTE_TO_SECURITY';route='Security';response='Report the suspected phishing/malware/unauthorized access incident immediately to security@veridian-corp.example. Do not forward the suspicious email to other employees.';break;
 case 'home_office': decision='ROUTE_TO_FINANCE';action='ROUTE_TO_FINANCE';route='Finance';response='Employees working remotely more than 3 days/week are eligible for a one-time home-office equipment allowance. Manager sign-off and Finance processing are required; IT handles shipping only after approval.';break;
 case 'laptop':
   decision='HUMAN_REVIEW_REQUIRED';action='ROUTE_TO_IT';route='IT Support';response='Laptop replacement depends on KB-03 and the Asset Management Policy. KB-03 covers eligibility after 3 years or verified hardware failure, while the Asset Management Policy states a 4-year refresh cycle and requires Finance sign-off for early replacement outside that cycle. The request should be reviewed with both policies visible.';break;
 case 'access': decision='HUMAN_REVIEW_REQUIRED';action='HUMAN_REVIEW_REQUIRED';route='IT Support';response='The supplied source data does not define a general admin-access approval policy. An earlier ticket was rejected for lack of business justification, but that historical record alone is not enough to invent a universal rule.';break;
 default: decision='HUMAN_REVIEW_REQUIRED';action='REQUEST_INFORMATION';response='I need more information about what is not working before I can apply a supported IT policy.';missing=['issue details'];
 }
 return {decision,action,route,response,missing};
}
exports.process=async(req)=>{
 const started=Date.now(); const c=classifier.classify(req.requestText); const matched= c.matchedPolicies.map(id=>policy.get(id)).filter(Boolean).map(p=>p.kbId); if(c.matchedPolicies.includes('ASSET-2026')) matched.push('ASSET-2026');
 const d=decide(req,c); audit.log({action:'REQUEST_CLASSIFIED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,reason:`Classified as ${c.category}`});
 if(matched.length) audit.log({action:'POLICY_MATCHED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,reason:'Relevant source policy identified'});
 let linkedTicketId=req.linkedTicketId||null;
 if(['CREATE_TICKET','ROUTE_TO_IT','ROUTE_TO_SECURITY','ROUTE_TO_FINANCE'].includes(d.action) && d.category!=='vpn' && d.category!=='email'){
   const t=ticket.create({request:req,category:c.category,status:d.action==='ROUTE_TO_SECURITY'?'In Progress':'Open',team:d.route,policies:matched,reason:d.response}); linkedTicketId=t.ticketId;
 }
 const now=new Date().toISOString(); const status=d.decision==='RESOLVE'?'Resolved':d.decision==='NO_TICKET_REQUIRED'?'Resolved':d.action==='REQUEST_INFORMATION'?'Needs Information':d.route==='Security'?'Escalated': 'In Progress';
 const updated=requests.update('requestId',req.requestId,{category:c.category,matchedPolicies:matched,classificationConfidence:c.confidence,recommendedAction:d.action,status,linkedTicketId,agentResponse:d.response,requiresHumanReview:d.decision==='HUMAN_REVIEW_REQUIRED',routedTo:d.route||null});
 if(d.decision==='RESOLVE'||d.decision==='NO_TICKET_REQUIRED') audit.log({action:'REQUEST_RESOLVED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,newState:status,reason:d.response}); else if(d.route==='Security') audit.log({action:'SECURITY_ESCALATED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,reason:d.response}); else if(d.decision==='HUMAN_REVIEW_REQUIRED') audit.log({action:'HUMAN_REVIEW_REQUIRED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,reason:d.response}); else audit.log({action:'REQUEST_ROUTED',entityType:'request',entityId:req.requestId,requestId:req.requestId,matchedPolicyIds:matched,reason:d.response});
 const run=agentRuns.insert({runId:randomUUID(),requestId:req.requestId,inputText:req.requestText,detectedCategory:c.category,matchedPolicies:matched,decision:d.decision,response:d.response,action:d.action,requiresHumanReview:d.decision==='HUMAN_REVIEW_REQUIRED',routedTo:d.route||null,confidence:c.confidence,processingTimeMs:Date.now()-started,createdAt:now});
 return {request:updated,run};
};
exports.findContext=(req)=>tickets.all().filter(t=>t.category===req.category||t.employeeEmail===req.employeeEmail).slice(-5);
